#  Copyright (c) 2012-2013, Pfadibewegung Schweiz. This file is part of
#  hitobito_pbs and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_pbs.

# Settings relevant for the jubla wagon
# Overrides settings from the main application
application:
  #name: Pfadi

  languages:
    de: Deutsch
    fr: Français
    it: Italiano
